# Generated by Django 5.2.5 on 2025-12-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_number', models.IntegerField()),
                ('title', models.CharField(max_length=100, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': '同类问题分组',
                'verbose_name_plural': '同类问题分组',
            },
        ),
    ]
