# Generated by Django 5.2.5 on 2025-12-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bug标题'),
        ),
    ]
