# Generated by Django 5.2.5 on 2025-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0002_alter_bug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_number',
            field=models.IntegerField(unique=True),
        ),
    ]
