# Generated by Django 5.2.5 on 2025-12-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0004_bug_created_at_bug_created_by_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
