# Generated by Django 5.2.5 on 2025-12-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0005_alter_bug_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='created_at',
        ),
    ]
