# Generated by Django 5.2.5 on 2025-12-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0006_remove_bug_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
