# Generated by Django 5.2.5 on 2025-12-30 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0007_bug_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
