# Generated by Django 5.2.5 on 2026-01-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_group', '0008_alter_bug_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
