# Generated by Django 5.2.5 on 2025-12-18 06:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=150, unique=True)),
                ('hardware_version', models.CharField(blank=True, max_length=150, null=True)),
                ('project', models.CharField(blank=True, max_length=150, null=True)),
                ('software_version', models.CharField(blank=True, max_length=150, null=True)),
                ('config', models.CharField(blank=True, max_length=150, null=True)),
                ('fail_station', models.CharField(blank=True, max_length=150, null=True)),
                ('failure_mode', models.CharField(blank=True, max_length=150, null=True)),
                ('test_link', models.CharField(blank=True, max_length=150, null=True)),
                ('current_position', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnalysisResults',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('analysis_notes', models.TextField()),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='判断结果（仅分支节点需填写）')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical analysis results',
                'verbose_name_plural': 'historical analysis resultss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=150)),
                ('hardware_version', models.CharField(blank=True, max_length=150, null=True)),
                ('project', models.CharField(blank=True, max_length=150, null=True)),
                ('software_version', models.CharField(blank=True, max_length=150, null=True)),
                ('config', models.CharField(blank=True, max_length=150, null=True)),
                ('fail_station', models.CharField(blank=True, max_length=150, null=True)),
                ('failure_mode', models.CharField(blank=True, max_length=150, null=True)),
                ('test_link', models.CharField(blank=True, max_length=150, null=True)),
                ('current_position', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical device',
                'verbose_name_plural': 'historical devices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径/链接')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_notes', models.TextField()),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='判断结果（仅分支节点需填写）')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
