# Generated by Django 5.2.5 on 2025-12-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('problem_group', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.deviceprocess'),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.devicetask'),
        ),
        migrations.AddField(
            model_name='device',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_group.bug'),
        ),
        migrations.AddField(
            model_name='device',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='workflows.deviceprocess'),
        ),
        migrations.AddField(
            model_name='historicalanalysisresults',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisresults',
            name='number',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalysisresults',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.deviceprocess'),
        ),
        migrations.AddField(
            model_name='historicalanalysisresults',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.devicetask'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='bug',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='problem_group.bug'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.deviceprocess'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.deviceprocess'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.devicetask'),
        ),
        migrations.AddField(
            model_name='historicalanalysisresults',
            name='operation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='⚠️ 请务必选择与“设备SN”对应的操作记录，避免关联错误！', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.operationrecord'),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='operation',
            field=models.ForeignKey(help_text='⚠️ 请务必选择与“设备SN”对应的操作记录，避免关联错误！', on_delete=django.db.models.deletion.CASCADE, to='devices.operationrecord'),
        ),
    ]
