# Generated by Django 5.2.5 on 2025-12-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('problem_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem_group.bug'),
        ),
    ]
