# Generated by Django 5.2.5 on 2025-12-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='test_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='test_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
