# Generated by Django 5.2.5 on 2025-12-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_positiontracking'),
        ('problem_group', '0006_remove_bug_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='problem_group.bug'),
        ),
    ]
