# Generated by Django 5.2.5 on 2026-01-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_bug'),
        ('workflows', '0002_remove_devicetask_analysis_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='process',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='process',
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.devicetask'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.devicetask'),
        ),
    ]
