# Generated by Django 5.2.5 on 2026-01-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_device_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresults',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='historicalanalysisresults',
            name='task_name',
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='result',
            field=models.BooleanField(blank=True, null=True, verbose_name='分析结果'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalanalysisresults',
            name='result',
            field=models.BooleanField(blank=True, null=True, verbose_name='分析结果'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='sn',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径/链接'),
        ),
    ]
