# Generated by Django 5.2.5 on 2025-12-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('devices', '0001_initial'),
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_processes', to='departments.department', verbose_name='当前处理部门')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processes', to='devices.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备处理流程实例',
                'verbose_name_plural': '设备处理流程实例列表',
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='DeviceTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.task')),
                ('data_submitted', models.BooleanField(default=False, verbose_name='是否已提交数据')),
                ('analysis_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_task', to='devices.analysisresults', verbose_name='关联分析结果')),
                ('operation_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_task', to='devices.operationrecord', verbose_name='关联操作记录')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.task',),
        ),
    ]
