"""
Django settings for abnormal_device_tracking project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# 加载.env
import os
from dotenv import load_dotenv
load_dotenv()  # 加载.env文件的变量

from pathlib import Path
# part 1 核心标识 : BASE_DIR SECRET_KEY  DEBUG ALLOWED_HOSTS
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 优先读取环境变量，无则用开发环境默认值（避免报错）
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-(6mn1t&&93t^!&3^w%b41_(o*xi1_1zbl-o)g_s7%((*v1v$-d)'
)

# SECURITY WARNING: don't run with debug turned on in production!
# 从环境变量读取DEBUG（默认False，生产安全），开发环境在.env里设DEBUG = True
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

if DEBUG: # 开发环境
    ALLOWED_HOSTS = []
else:  # 生产环境
    ALLOWED_HOSTS = ['120.76.137.120', '127.0.0.1', 'localhost']
# Application definition

# part 2 应用与中间件（核心运行依赖）
INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    'viewflow',
    'viewflow.workflow',
    'accounts',
    'departments',
    'devices',
    'workflows',
    'notifications',
    'chat',
    'problem_group'
]
MIDDLEWARE = [
    # 请求追踪放在最前面，确保所有后续处理都能用到request_id
    'abnormal_device_tracking.middleware.RequestIDMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # 必须有这一行
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 性能监控
    'abnormal_device_tracking.middleware.PerformanceMiddleware',
    # workflow权限校验
    'workflows.middleware.NodePermissionMiddleware',
    'workflows.middleware.ThreadLocalMiddleware',

]




# part 3  URL 与模板（路由/视图基础）
ROOT_URLCONF = 'abnormal_device_tracking.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
            ],
        },
    },
]


# part 4  部署入口
WSGI_APPLICATION = 'abnormal_device_tracking.wsgi.application'
ASGI_APPLICATION = "abnormal_device_tracking.asgi.application"
# django channel通道层配置
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",# 这里选channels_redis实现
        "CONFIG": {
            "hosts": [f"redis://:{os.environ['REDIS_PASSWORD']}@127.0.0.1:6379/0"],
        },
    },
}

# 指定唯一用户模型
AUTH_USER_MODEL = 'accounts.Employee'


# part 5  数据库（默认SQLite）,指定项目使用的数据库（SQLite/MySQL/PostgreSQL 等）
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 数据库配置，默认使用SQLite作为开发数据库
if 'DATABASE_URL' in os.environ:
    # 生产环境
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    }
else:
    # 开发环境：默认使用SQLite
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME'),
            'USER': os.getenv('DATABASE_USER'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# part 6  密码验证（认证安全）
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# part 7  国际化（语言/时区）
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# part 8  静态文件（CSS/JS/图片）
# 静态文件配置
STATIC_URL = '/static/'
if DEBUG:# 开发环境
    STATICFILES_DIRS = [BASE_DIR / 'static'] # 开发环境
else:  # 生产环境
    STATIC_ROOT = BASE_DIR / 'staticfiles'  # 生产环境下告诉 Django「collectstatic 要把所有静态文件汇总到哪个目录」



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# part 9  日志配置
# 配置logging，确保能看到中间件的日志
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# ===== 部署安全配置、生产环境下的安全项配置  =====
# 1. 如果站点确定只使用HTTPS后，可启用HSTS（高级安全协议）。
# SECURE_HSTS_PRELOAD = True  # 允许浏览器预加载HSTS列表

# 2. SSL/HTTPS 配置
# SECURE_SSL_REDIRECT = False  # True表示将所有HTTP请求重定向到HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 信任Render等代理的HTTPS头

# 3. Cookie安全
# SESSION_COOKIE_SECURE = False   # True表示会话CSRF_COOKIE_SECUREookie仅通过HTTPS传输
# CSRF_COOKIE_SECURE = False      # True表示CSRF令牌Cookie仅通过HTTPS传输

# 4. 其他安全增强
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'  # 防止网站在iframe中被嵌入，防点击劫持

