"""
Django settings for abnormal_device_tracking project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(6mn1t&&93t^!&3^w%b41_(o*xi1_1zbl-o)g_s7%((*v1v$-d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    'viewflow',
    'viewflow.workflow',
    'accounts',
    'departments',
    'devices',
    'workflows',
    'notifications',
    'chat',
    'problem_group'
]

ASGI_APPLICATION = "abnormal_device_tracking.asgi.application"
# 配置聊天室通道层
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://:{os.environ['REDIS_PASSWORD']}@127.0.0.1:6379/0"],
        },
    },
}

# 指定唯一用户模型
AUTH_USER_MODEL = 'accounts.Employee'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'workflows.middleware.NodePermissionMiddleware',
    'workflows.middleware.ThreadLocalMiddleware',

]

ROOT_URLCONF = 'abnormal_device_tracking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
            ],
        },
    },
]



WSGI_APPLICATION = 'abnormal_device_tracking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


import os
# 数据库配置，默认使用SQLite作为开发数据库
if 'DATABASE_URL' in os.environ:
    # 生产环境
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=os.environ['DATABASE_URL'])
    }
else:
    # 开发环境：默认使用SQLite
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DATABASE_NAME'],
            'USER': os.environ['DATABASE_USER'],
            'PASSWORD': os.environ['DATABASE_PASSWORD'],
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# 根据环境变量判断是否调试模式
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ===== 部署安全配置 - 完整版 =====
# 0. 密钥管理（最重要！）：从环境变量读取，不要在代码中写死。
#    在Render控制台的Environment中设置名为 SECRET_KEY 的变量。
import os
from dotenv import load_dotenv
# 加载 .env 文件中的环境变量
load_dotenv()
SECRET_KEY = os.environ['SECRET_KEY']  # 如果环境变量不存在会报错

# 1. 如果站点确定只使用HTTPS后，可启用HSTS（高级安全协议）。
#    首次部署可先设为0或一个较小的值（如3600秒）进行测试。
SECURE_HSTS_SECONDS = 0  # 先禁用。确认HTTPS工作正常后，可设置为31536000（1年）
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 强制所有子域名也使用HTTPS
SECURE_HSTS_PRELOAD = True  # 允许浏览器预加载HSTS列表

# 2. SSL/HTTPS 配置
SECURE_SSL_REDIRECT = True  # 将所有HTTP请求重定向到HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 信任Render等代理的HTTPS头

# 3. Cookie安全
SESSION_COOKIE_SECURE = True   # 会话Cookie仅通过HTTPS传输
CSRF_COOKIE_SECURE = True      # CSRF令牌Cookie仅通过HTTPS传输

# 4. 其他安全增强
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # 防止网站在iframe中被嵌入，防点击劫持

# 5. 生产环境域名白名单
ALLOWED_HOSTS = [
    '.onrender.com',       # 允许所有onrender.com的子域名
    # 'your-custom-domain.com', # 如果有自定义域名，在这里添加
    'localhost',
    '127.0.0.1',
    '[::1]',               # IPv6本地地址
]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' # 生产环境下告诉 Django「collectstatic 要把所有静态文件汇总到哪个目录」

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
