# Generated by Django 5.2.5 on 2025-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, help_text="聊天室唯一标识，如'process_123'或'bug_456'", max_length=255, null=True, unique=True),
        ),
    ]
