# Generated by Django 5.2.5 on 2025-12-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('manager_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_departments', to=settings.AUTH_USER_MODEL, to_field='number')),
            ],
        ),
    ]
